
(myvenv20) C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20> cd ..

(myvenv20) C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic>pip install django~=3.2.10
Collecting django~=3.2.10
  Downloading Django-3.2.25-py3-none-any.whl (7.9 MB)
     |████████████████████████████████| 7.9 MB 6.4 MB/s
Collecting asgiref<4,>=3.3.2
  Downloading asgiref-3.9.2-py3-none-any.whl (23 kB)
Collecting pytz
  Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
     |████████████████████████████████| 509 kB ...
Collecting sqlparse>=0.2.2
  Downloading sqlparse-0.5.3-py3-none-any.whl (44 kB)
     |████████████████████████████████| 44 kB 3.4 MB/s
Collecting typing_extensions>=4
  Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
     |████████████████████████████████| 44 kB 1.1 MB/s
Installing collected packages: typing-extensions, sqlparse, pytz, asgiref, django
Successfully installed asgiref-3.9.2 django-3.2.25 pytz-2025.2 sqlparse-0.5.3 typing-extensions-4.15.0
WARNING: You are using pip version 21.2.4; however, version 25.2 is available.
You should consider upgrading via the 'C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\Scripts\python.exe -m pip install --upgrade pip' command.

(myvenv20) C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic>django-admin startproject myweb .

(myvenv20) C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic>python manage.py startapp photo

(myvenv20) C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
September 25, 2025 - 15:26:31
Django version 3.2.25, using settings 'myweb.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[25/Sep/2025 15:26:42] "GET / HTTP/1.1" 200 10697
[25/Sep/2025 15:26:42] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[25/Sep/2025 15:26:42] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
[25/Sep/2025 15:26:42] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
Not Found: /favicon.ico
[25/Sep/2025 15:26:42] "GET /favicon.ico HTTP/1.1" 404 2109
[25/Sep/2025 15:26:42] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myweb\settings.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
September 25, 2025 - 15:28:07
Django version 3.2.25, using settings 'myweb.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myweb\settings.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
September 25, 2025 - 15:29:25
Django version 3.2.25, using settings 'myweb.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[25/Sep/2025 15:30:23] "GET /admin HTTP/1.1" 301 0
[25/Sep/2025 15:30:23] "GET /admin/ HTTP/1.1" 302 0
[25/Sep/2025 15:30:26] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2218
[25/Sep/2025 15:30:26] "GET /static/admin/css/login.css HTTP/1.1" 200 939
[25/Sep/2025 15:30:26] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2271
[25/Sep/2025 15:30:26] "GET /static/admin/css/base.css HTTP/1.1" 200 19513
[25/Sep/2025 15:30:26] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[25/Sep/2025 15:30:26] "GET /static/admin/css/responsive.css HTTP/1.1" 200 18545
[25/Sep/2025 15:30:26] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[25/Sep/2025 15:30:26] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[25/Sep/2025 15:30:26] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 1360

(myvenv20) C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic>cd //
지정된 경로를 찾을 수 없습니다.

(myvenv20) C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic>cd ..

(myvenv20) C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project>python manage.py migrate
C:\Users\admin\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'C:\\Users\\admin\\Desktop\\dev\\Python-Practice\\django\\DRF_project\\manage.py': [Errno 2] No such file or directory

(myvenv20) C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project>cd myvenv20
지정된 경로를 찾을 수 없습니다.

(myvenv20) C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project>cd ch02_DRF_basic

(myvenv20) C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
September 25, 2025 - 15:39:58
Django version 3.2.25, using settings 'myweb.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[25/Sep/2025 15:40:10] "GET / HTTP/1.1" 200 10697
[25/Sep/2025 15:40:10] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[25/Sep/2025 15:40:10] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[25/Sep/2025 15:40:10] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[25/Sep/2025 15:40:10] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[25/Sep/2025 15:40:13] "GET /admin/ HTTP/1.1" 302 0
[25/Sep/2025 15:40:13] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2218
[25/Sep/2025 15:40:13] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[25/Sep/2025 15:40:13] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[25/Sep/2025 15:40:13] "GET /static/admin/css/login.css HTTP/1.1" 304 0
[25/Sep/2025 15:40:13] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[25/Sep/2025 15:40:13] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0

(myvenv20) C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic>python manage.py createsuperuser

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: auth_user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\manage.py", line 22, in <module>
    main()
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\management\__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\contrib\auth\management\commands\createsuperuser.py", line 79, in execute
    return super().execute(*args, **options)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\contrib\auth\management\commands\createsuperuser.py", line 100, in handle
    default_username = get_default_username(database=database)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\contrib\auth\management\__init__.py", line 141, in get_default_username
    auth_app.User._default_manager.db_manager(database).get(
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\db\backends\utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: auth_user

(myvenv20) C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic>cd ..

(myvenv20) C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project>python manage.py createsuperuser
C:\Users\admin\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'C:\\Users\\admin\\Desktop\\dev\\Python-Practice\\django\\DRF_project\\manage.py': [Errno 2] No such file or directory

(myvenv20) C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project>python manage.py migrate
C:\Users\admin\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'C:\\Users\\admin\\Desktop\\dev\\Python-Practice\\django\\DRF_project\\manage.py': [Errno 2] No such file or directory

(myvenv20) C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project>cd ch02_DRF_basic

(myvenv20) C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying sessions.0001_initial... OK

(myvenv20) C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic>python manage.py createsuperuser
Username (leave blank to use 'admin'): admin
Email address: admin@admin
Error: Enter a valid email address.
Email address: admin@admin.com
Password:
Password (again):
This password is too short. It must contain at least 8 characters.
This password is too common.
This password is entirely numeric.
Bypass password validation and create user anyway? [y/N]: Y
Superuser created successfully.

(myvenv20) C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 25, 2025 - 15:43:42
Django version 3.2.25, using settings 'myweb.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[25/Sep/2025 15:43:45] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2218
[25/Sep/2025 15:43:45] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[25/Sep/2025 15:43:45] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[25/Sep/2025 15:43:45] "GET /static/admin/css/login.css HTTP/1.1" 304 0
[25/Sep/2025 15:43:45] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[25/Sep/2025 15:43:45] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[25/Sep/2025 15:43:45] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[25/Sep/2025 15:43:45] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[25/Sep/2025 15:43:45] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[25/Sep/2025 15:43:48] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[25/Sep/2025 15:43:48] "GET /admin/ HTTP/1.1" 200 3330
[25/Sep/2025 15:43:48] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[25/Sep/2025 15:43:48] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 380
[25/Sep/2025 15:43:48] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[25/Sep/2025 15:43:48] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[25/Sep/2025 15:45:54] "GET /admin/ HTTP/1.1" 200 3330
[25/Sep/2025 15:45:55] "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
[25/Sep/2025 15:45:55] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[25/Sep/2025 15:45:55] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[25/Sep/2025 15:45:55] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[25/Sep/2025 15:45:55] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[25/Sep/2025 15:45:55] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[25/Sep/2025 15:45:55] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[25/Sep/2025 15:45:55] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[25/Sep/2025 15:45:55] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[25/Sep/2025 15:45:55] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[25/Sep/2025 15:45:55] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[25/Sep/2025 15:45:57] "GET /admin/login/?next=/admin/ HTTP/1.1" 302 0
[25/Sep/2025 15:45:57] "GET /admin/ HTTP/1.1" 200 3330
[25/Sep/2025 15:45:58] "GET /admin/auth/group/add/ HTTP/1.1" 200 7622
[25/Sep/2025 15:45:58] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[25/Sep/2025 15:45:58] "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
[25/Sep/2025 15:45:58] "GET /static/admin/css/forms.css HTTP/1.1" 200 8804
[25/Sep/2025 15:45:58] "GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4360
[25/Sep/2025 15:45:58] "GET /static/admin/css/widgets.css HTTP/1.1" 200 11097
[25/Sep/2025 15:45:58] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 5984
[25/Sep/2025 15:45:58] "GET /static/admin/js/core.js HTTP/1.1" 200 5698
[25/Sep/2025 15:45:58] "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 12350
[25/Sep/2025 15:45:58] "GET /static/admin/js/actions.js HTTP/1.1" 200 7867
[25/Sep/2025 15:45:58] "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
[25/Sep/2025 15:45:58] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 492
[25/Sep/2025 15:45:58] "GET /static/admin/js/urlify.js HTTP/1.1" 200 7902
[25/Sep/2025 15:45:58] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 287630
[25/Sep/2025 15:45:58] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
[25/Sep/2025 15:45:58] "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
[25/Sep/2025 15:45:58] "GET /static/admin/img/search.svg HTTP/1.1" 200 458
[25/Sep/2025 15:45:58] "GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
[25/Sep/2025 15:45:58] "GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
[25/Sep/2025 15:45:58] "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
[25/Sep/2025 15:46:01] "GET /admin/ HTTP/1.1" 200 3330
[25/Sep/2025 15:46:05] "GET / HTTP/1.1" 200 10697

(myvenv20) C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic>python manage.py makemigrations
No changes detected

(myvenv20) C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic>python manage.py makemigrations
Migrations for 'photo':
  photo\migrations\0001_initial.py
    - Create model Photo

(myvenv20) C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, photo, sessions
Running migrations:
  Applying photo.0001_initial... OK

(myvenv20) C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 25, 2025 - 15:50:04
Django version 3.2.25, using settings 'myweb.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[25/Sep/2025 15:50:09] "GET /admin/ HTTP/1.1" 200 3966
[25/Sep/2025 15:50:10] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[25/Sep/2025 15:50:10] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[25/Sep/2025 15:50:10] "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
[25/Sep/2025 15:50:10] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[25/Sep/2025 15:50:10] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[25/Sep/2025 15:50:10] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[25/Sep/2025 15:50:10] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[25/Sep/2025 15:50:10] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[25/Sep/2025 15:50:10] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[25/Sep/2025 15:50:10] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[25/Sep/2025 15:50:10] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[25/Sep/2025 15:50:16] "GET /admin/photo/photo/ HTTP/1.1" 200 4920
[25/Sep/2025 15:50:16] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[25/Sep/2025 15:50:16] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[25/Sep/2025 15:50:16] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[25/Sep/2025 15:50:16] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[25/Sep/2025 15:50:16] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[25/Sep/2025 15:50:16] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[25/Sep/2025 15:50:16] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[25/Sep/2025 15:50:16] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[25/Sep/2025 15:50:16] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
[25/Sep/2025 15:50:16] "GET /static/admin/css/changelists.css HTTP/1.1" 200 6874
[25/Sep/2025 15:50:16] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
[25/Sep/2025 15:50:27] "GET /admin/photo/photo/add/ HTTP/1.1" 200 7545
[25/Sep/2025 15:50:27] "GET /static/admin/css/forms.css HTTP/1.1" 304 0
[25/Sep/2025 15:50:27] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
[25/Sep/2025 15:50:27] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[25/Sep/2025 15:50:27] "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
[25/Sep/2025 15:50:27] "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
[25/Sep/2025 15:50:35] "POST /admin/photo/photo/add/ HTTP/1.1" 200 7909
[25/Sep/2025 15:50:35] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[25/Sep/2025 15:53:02] "POST /admin/photo/photo/add/ HTTP/1.1" 302 0
[25/Sep/2025 15:53:02] "GET /admin/photo/photo/ HTTP/1.1" 200 6277
[25/Sep/2025 15:53:02] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[25/Sep/2025 15:53:02] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[25/Sep/2025 15:53:02] "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
[25/Sep/2025 15:53:02] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[25/Sep/2025 15:53:02] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[25/Sep/2025 15:53:02] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[25/Sep/2025 15:53:02] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[25/Sep/2025 15:53:02] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[25/Sep/2025 15:53:02] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[25/Sep/2025 15:53:02] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[25/Sep/2025 15:53:02] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[25/Sep/2025 15:53:02] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[25/Sep/2025 15:53:02] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[25/Sep/2025 15:53:02] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
[25/Sep/2025 15:53:02] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[25/Sep/2025 15:53:02] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
[25/Sep/2025 15:53:02] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[25/Sep/2025 15:53:02] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[25/Sep/2025 15:53:02] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[25/Sep/2025 15:53:02] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[25/Sep/2025 15:53:02] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
[25/Sep/2025 15:53:04] "GET /admin/photo/photo/1/change/ HTTP/1.1" 200 7923
[25/Sep/2025 15:53:04] "GET /static/admin/css/forms.css HTTP/1.1" 304 0
[25/Sep/2025 15:53:04] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
[25/Sep/2025 15:53:04] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[25/Sep/2025 15:53:04] "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
[25/Sep/2025 15:53:04] "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
[25/Sep/2025 15:53:05] "POST /admin/photo/photo/1/change/ HTTP/1.1" 302 0
[25/Sep/2025 15:53:05] "GET /admin/photo/photo/ HTTP/1.1" 200 6279
[25/Sep/2025 15:53:05] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[25/Sep/2025 15:55:08] "GET /admin/photo/photo/1/change/ HTTP/1.1" 200 7923
[25/Sep/2025 15:55:08] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[25/Sep/2025 15:55:39] "POST /admin/photo/photo/1/change/ HTTP/1.1" 302 0
[25/Sep/2025 15:55:39] "GET /admin/photo/photo/ HTTP/1.1" 200 6279
[25/Sep/2025 15:55:39] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[25/Sep/2025 15:55:41] "GET /admin/photo/photo/1/change/ HTTP/1.1" 200 7933
[25/Sep/2025 15:55:41] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[25/Sep/2025 15:55:43] "POST /admin/photo/photo/1/change/ HTTP/1.1" 302 0
[25/Sep/2025 15:55:43] "GET /admin/photo/photo/ HTTP/1.1" 200 6279
[25/Sep/2025 15:55:43] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myweb\urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\management\commands\runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\management\base.py", line 419, in check
    all_issues = checks.run_checks(
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\checks\registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\urls\resolvers.py", line 416, in check
    for pattern in self.url_patterns:
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\urls\resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\urls\resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myweb\urls.py", line 21, in <module>
    path('', include('photo.urls')),
NameError: name 'include' is not defined
C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myweb\urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 25, 2025 - 16:03:03
Django version 3.2.25, using settings 'myweb.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[25/Sep/2025 16:03:07] "GET / HTTP/1.1" 200 713
[25/Sep/2025 16:03:09] "GET / HTTP/1.1" 200 713
[25/Sep/2025 16:03:10] "GET / HTTP/1.1" 200 713
[25/Sep/2025 16:03:10] "GET / HTTP/1.1" 200 713
[25/Sep/2025 16:03:11] "GET / HTTP/1.1" 200 713
[25/Sep/2025 16:03:12] "GET / HTTP/1.1" 200 713
[25/Sep/2025 16:03:12] "GET / HTTP/1.1" 200 713
[25/Sep/2025 16:03:13] "GET / HTTP/1.1" 200 713
[25/Sep/2025 16:03:13] "GET / HTTP/1.1" 200 713
[25/Sep/2025 16:03:14] "GET / HTTP/1.1" 200 713
[25/Sep/2025 16:03:14] "GET / HTTP/1.1" 200 713
[25/Sep/2025 16:03:16] "GET /admin/ HTTP/1.1" 200 5172
[25/Sep/2025 16:03:16] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[25/Sep/2025 16:03:16] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[25/Sep/2025 16:03:16] "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
[25/Sep/2025 16:03:16] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[25/Sep/2025 16:03:16] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[25/Sep/2025 16:03:16] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[25/Sep/2025 16:03:16] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[25/Sep/2025 16:03:16] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[25/Sep/2025 16:03:16] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[25/Sep/2025 16:03:16] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[25/Sep/2025 16:03:16] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[25/Sep/2025 16:03:18] "GET /admin/photo/photo/ HTTP/1.1" 200 6072
[25/Sep/2025 16:03:18] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[25/Sep/2025 16:03:18] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[25/Sep/2025 16:03:18] "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
[25/Sep/2025 16:03:18] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[25/Sep/2025 16:03:18] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[25/Sep/2025 16:03:18] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[25/Sep/2025 16:03:18] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[25/Sep/2025 16:03:18] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[25/Sep/2025 16:03:18] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
[25/Sep/2025 16:03:18] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[25/Sep/2025 16:03:18] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
[25/Sep/2025 16:03:19] "GET /admin/photo/photo/1/change/ HTTP/1.1" 200 7933
[25/Sep/2025 16:03:19] "GET /static/admin/css/forms.css HTTP/1.1" 304 0
[25/Sep/2025 16:03:19] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
[25/Sep/2025 16:03:19] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[25/Sep/2025 16:03:19] "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
[25/Sep/2025 16:03:19] "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
[25/Sep/2025 16:03:27] "POST /admin/photo/photo/1/change/ HTTP/1.1" 302 0
[25/Sep/2025 16:03:27] "GET /admin/photo/photo/ HTTP/1.1" 200 6279
[25/Sep/2025 16:03:27] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[25/Sep/2025 16:03:27] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
[25/Sep/2025 16:03:31] "GET / HTTP/1.1" 200 713
[25/Sep/2025 16:06:25] "GET / HTTP/1.1" 200 177
[25/Sep/2025 16:06:26] "GET / HTTP/1.1" 200 177
[25/Sep/2025 16:06:26] "GET / HTTP/1.1" 200 177
[25/Sep/2025 16:06:27] "GET / HTTP/1.1" 200 177
[25/Sep/2025 16:06:27] "GET / HTTP/1.1" 200 177
[25/Sep/2025 16:06:27] "GET / HTTP/1.1" 200 177
[25/Sep/2025 16:06:27] "GET / HTTP/1.1" 200 177
[25/Sep/2025 16:06:27] "GET / HTTP/1.1" 200 177
[25/Sep/2025 16:06:28] "GET / HTTP/1.1" 200 177
[25/Sep/2025 16:06:28] "GET / HTTP/1.1" 200 177
[25/Sep/2025 16:06:28] "GET / HTTP/1.1" 200 177
[25/Sep/2025 16:06:29] "GET / HTTP/1.1" 200 177
[25/Sep/2025 16:06:30] "GET / HTTP/1.1" 200 177
[25/Sep/2025 16:06:30] "GET / HTTP/1.1" 200 177
[25/Sep/2025 16:06:31] "GET / HTTP/1.1" 200 177
[25/Sep/2025 16:06:31] "GET / HTTP/1.1" 200 177
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\views.py", line 5, in photo_list
    return render(request, 'photo/photo_list.html', {})
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\template\defaulttags.py", line 817, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\template\base.py", line 483, in parse
    self.unclosed_block_tag(parse_until)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\template\base.py", line 544, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 8: 'for'. Looking for one of: empty, endfor.
[25/Sep/2025 16:06:41] "GET / HTTP/1.1" 500 134547
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\views.py", line 5, in photo_list
    return render(request, 'photo/photo_list.html', {})
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\template\defaulttags.py", line 817, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\template\base.py", line 483, in parse
    self.unclosed_block_tag(parse_until)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\template\base.py", line 544, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 8: 'for'. Looking for one of: empty, endfor.
[25/Sep/2025 16:06:41] "GET / HTTP/1.1" 500 134547
[25/Sep/2025 16:07:49] "GET / HTTP/1.1" 200 177
[25/Sep/2025 16:07:50] "GET / HTTP/1.1" 200 177
[25/Sep/2025 16:07:50] "GET / HTTP/1.1" 200 177
[25/Sep/2025 16:07:50] "GET / HTTP/1.1" 200 177
[25/Sep/2025 16:07:50] "GET / HTTP/1.1" 200 177
[25/Sep/2025 16:07:51] "GET / HTTP/1.1" 200 177
[25/Sep/2025 16:07:51] "GET / HTTP/1.1" 200 177
[25/Sep/2025 16:07:52] "GET / HTTP/1.1" 200 177
[25/Sep/2025 16:07:52] "GET / HTTP/1.1" 200 177
[25/Sep/2025 16:07:52] "GET / HTTP/1.1" 200 177
[25/Sep/2025 16:07:53] "GET / HTTP/1.1" 200 177
[25/Sep/2025 16:07:53] "GET / HTTP/1.1" 200 177
C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 25, 2025 - 16:09:47
Django version 3.2.25, using settings 'myweb.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[25/Sep/2025 16:09:50] "GET / HTTP/1.1" 200 449
[25/Sep/2025 16:09:51] "GET / HTTP/1.1" 200 449
[25/Sep/2025 16:09:51] "GET / HTTP/1.1" 200 449
[25/Sep/2025 16:09:52] "GET / HTTP/1.1" 200 449
[25/Sep/2025 16:09:52] "GET / HTTP/1.1" 200 449
[25/Sep/2025 16:09:52] "GET / HTTP/1.1" 200 449
[25/Sep/2025 16:09:52] "GET / HTTP/1.1" 200 449
[25/Sep/2025 16:09:53] "GET / HTTP/1.1" 200 449
[25/Sep/2025 16:09:53] "GET / HTTP/1.1" 200 449
[25/Sep/2025 16:09:54] "GET / HTTP/1.1" 200 449
[25/Sep/2025 16:09:54] "GET / HTTP/1.1" 200 449
[25/Sep/2025 16:09:54] "GET / HTTP/1.1" 200 449
C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 25, 2025 - 16:27:55
Django version 3.2.25, using settings 'myweb.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\urls\resolvers.py", line 242, in _route_to_regex
    converter = get_converter(raw_converter)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\urls\converters.py", line 66, in get_converter
    return get_converters()[raw_converter]
KeyError: 'ink'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\management\commands\runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\management\base.py", line 419, in check
    all_issues = checks.run_checks(
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\checks\registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\urls\resolvers.py", line 416, in check
    for pattern in self.url_patterns:
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\urls\resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\urls\resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myweb\urls.py", line 21, in <module>
    path('', include('photo.urls')),
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\urls.py", line 10, in <module>
    path('photo/<ink:pk>/', views.photo_detail, name='photo_detail'),
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\urls\conf.py", line 70, in _path
    pattern = Pattern(route, name=name, is_endpoint=True)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\urls\resolvers.py", line 263, in __init__
    self.converters = _route_to_regex(str(route), is_endpoint)[1]
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\urls\resolvers.py", line 244, in _route_to_regex
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: URL route 'photo/<ink:pk>/' uses invalid converter 'ink'.

(myvenv20) C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 25, 2025 - 16:32:11
Django version 3.2.25, using settings 'myweb.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[25/Sep/2025 16:32:14] "GET /admin/ HTTP/1.1" 200 5466
[25/Sep/2025 16:32:14] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[25/Sep/2025 16:32:14] "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
[25/Sep/2025 16:32:14] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[25/Sep/2025 16:32:14] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[25/Sep/2025 16:32:14] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[25/Sep/2025 16:32:14] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[25/Sep/2025 16:32:14] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[25/Sep/2025 16:32:14] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[25/Sep/2025 16:32:14] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[25/Sep/2025 16:32:14] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[25/Sep/2025 16:32:14] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[25/Sep/2025 16:32:16] "GET / HTTP/1.1" 200 420
[25/Sep/2025 16:32:18] "GET /photo/1/ HTTP/1.1" 200 332
[25/Sep/2025 16:32:21] "GET / HTTP/1.1" 200 420
[25/Sep/2025 16:32:21] "GET / HTTP/1.1" 200 420
[25/Sep/2025 16:32:22] "GET /photo/1/ HTTP/1.1" 200 332
[25/Sep/2025 16:32:25] "GET /photo/1/ HTTP/1.1" 200 332
[25/Sep/2025 16:32:27] "GET /photo/1/ HTTP/1.1" 200 332
[25/Sep/2025 16:35:59] "GET /photo/1/ HTTP/1.1" 200 326
C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\management\commands\runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\management\base.py", line 419, in check
    all_issues = checks.run_checks(
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\checks\registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\urls\resolvers.py", line 416, in check
    for pattern in self.url_patterns:
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\urls\resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\urls\resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myweb\urls.py", line 21, in <module>
    path('', include('photo.urls')),
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\urls.py", line 4, in <module>
    from . import views
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\views.py", line 3, in <module>
    from .forms import PhotoForm
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\forms.py", line 4, in <module>
    class PhotoForm(forms.ModelForm):
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\forms\models.py", line 250, in __new__
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form PhotoForm needs updating.

(myvenv20) C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\management\commands\runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\management\base.py", line 419, in check
    all_issues = checks.run_checks(
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\checks\registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\urls\resolvers.py", line 416, in check
    for pattern in self.url_patterns:
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\urls\resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\urls\resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myweb\urls.py", line 21, in <module>
    path('', include('photo.urls')),
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\urls.py", line 4, in <module>
    from . import views
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\views.py", line 3, in <module>
    from .forms import PhotoForm
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\forms.py", line 4, in <module>
    class PhotoForm(forms.ModelForm):
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\forms\models.py", line 250, in __new__
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form PhotoForm needs updating.

(myvenv20) C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic>^S

(myvenv20) C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic>

(myvenv20) C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 25, 2025 - 16:57:52
Django version 3.2.25, using settings 'myweb.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[25/Sep/2025 16:58:03] "GET /admin/ HTTP/1.1" 200 5466
[25/Sep/2025 16:58:03] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[25/Sep/2025 16:58:03] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[25/Sep/2025 16:58:03] "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
[25/Sep/2025 16:58:03] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[25/Sep/2025 16:58:03] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[25/Sep/2025 16:58:03] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[25/Sep/2025 16:58:03] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[25/Sep/2025 16:58:03] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[25/Sep/2025 16:58:03] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[25/Sep/2025 16:58:03] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[25/Sep/2025 16:58:03] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[25/Sep/2025 16:58:05] "GET /admin/ HTTP/1.1" 200 5466
[25/Sep/2025 16:58:06] "GET / HTTP/1.1" 200 463
Internal Server Error: /photo/new/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\handlers\base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\handlers\base.py", line 309, in check_response
    raise ValueError(
ValueError: The view photo.views.photo_post didn't return an HttpResponse object. It returned None instead.
[25/Sep/2025 16:58:08] "GET /photo/new/ HTTP/1.1" 500 65395
[25/Sep/2025 16:58:15] "GET /photo/1/ HTTP/1.1" 200 326
[25/Sep/2025 16:58:17] "GET / HTTP/1.1" 200 463
[25/Sep/2025 16:58:18] "GET / HTTP/1.1" 200 463
[25/Sep/2025 16:58:18] "GET / HTTP/1.1" 200 463
[25/Sep/2025 16:58:18] "GET / HTTP/1.1" 200 463
[25/Sep/2025 16:58:19] "GET / HTTP/1.1" 200 463
[25/Sep/2025 16:58:19] "GET / HTTP/1.1" 200 463
[25/Sep/2025 16:58:19] "GET / HTTP/1.1" 200 463
[25/Sep/2025 16:58:19] "GET / HTTP/1.1" 200 463
C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\management\commands\runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\management\base.py", line 419, in check
    all_issues = checks.run_checks(
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\checks\registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\urls\resolvers.py", line 416, in check
    for pattern in self.url_patterns:
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\urls\resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\urls\resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myweb\urls.py", line 21, in <module>
    path('', include('photo.urls')),
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\urls.py", line 9, in <module>
    path('', views.photo_list, name='photo_list'),
AttributeError: module 'photo.views' has no attribute 'photo_list'
C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 25, 2025 - 16:59:41
Django version 3.2.25, using settings 'myweb.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[25/Sep/2025 16:59:46] "GET /admin/photo/photo/ HTTP/1.1" 200 6072
[25/Sep/2025 16:59:46] "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
[25/Sep/2025 16:59:46] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[25/Sep/2025 16:59:46] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[25/Sep/2025 16:59:46] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[25/Sep/2025 16:59:46] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[25/Sep/2025 16:59:46] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
[25/Sep/2025 16:59:46] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[25/Sep/2025 16:59:46] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[25/Sep/2025 16:59:46] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[25/Sep/2025 16:59:46] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[25/Sep/2025 16:59:46] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
[25/Sep/2025 16:59:47] "GET /admin/photo/photo/1/change/ HTTP/1.1" 200 7933
[25/Sep/2025 16:59:47] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
[25/Sep/2025 16:59:47] "GET /static/admin/css/forms.css HTTP/1.1" 304 0
[25/Sep/2025 16:59:47] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[25/Sep/2025 16:59:47] "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
[25/Sep/2025 16:59:47] "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
[25/Sep/2025 16:59:52] "GET / HTTP/1.1" 200 463
Internal Server Error: /photo/new/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\handlers\base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\handlers\base.py", line 309, in check_response
    raise ValueError(
ValueError: The view photo.views.photo_post didn't return an HttpResponse object. It returned None instead.
[25/Sep/2025 16:59:53] "GET /photo/new/ HTTP/1.1" 500 65395
C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 25, 2025 - 17:01:08
Django version 3.2.25, using settings 'myweb.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[25/Sep/2025 17:01:15] "GET /photo/new/ HTTP/1.1" 200 1066
[25/Sep/2025 17:01:35] "POST /photo/new/ HTTP/1.1" 302 0
[25/Sep/2025 17:01:35] "GET /photo/2/ HTTP/1.1" 200 250
Not Found: /photo/2/고양이
[25/Sep/2025 17:01:35] "GET /photo/2/%EA%B3%A0%EC%96%91%EC%9D%B4 HTTP/1.1" 404 2676
[25/Sep/2025 17:02:23] "POST /photo/new/ HTTP/1.1" 302 0
[25/Sep/2025 17:02:23] "GET /photo/3/ HTTP/1.1" 200 288
[25/Sep/2025 17:03:23] "POST /photo/new/ HTTP/1.1" 302 0
[25/Sep/2025 17:03:23] "GET /photo/4/ HTTP/1.1" 200 441
[25/Sep/2025 17:03:43] "POST /photo/new/ HTTP/1.1" 302 0
[25/Sep/2025 17:03:43] "GET /photo/5/ HTTP/1.1" 200 445
[25/Sep/2025 17:04:23] "POST /photo/new/ HTTP/1.1" 302 0
[25/Sep/2025 17:04:23] "GET /photo/6/ HTTP/1.1" 200 441
[25/Sep/2025 17:04:29] "POST /photo/new/ HTTP/1.1" 302 0
[25/Sep/2025 17:04:29] "GET /photo/7/ HTTP/1.1" 200 445
[25/Sep/2025 17:04:59] "POST /photo/new/ HTTP/1.1" 302 0
[25/Sep/2025 17:04:59] "GET /photo/8/ HTTP/1.1" 200 273
[25/Sep/2025 17:05:23] "POST /photo/new/ HTTP/1.1" 302 0
[25/Sep/2025 17:05:23] "GET /photo/9/ HTTP/1.1" 200 282
C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 25, 2025 - 17:06:16
Django version 3.2.25, using settings 'myweb.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 25, 2025 - 17:09:04
Django version 3.2.25, using settings 'myweb.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\forms.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 25, 2025 - 17:10:46
Django version 3.2.25, using settings 'myweb.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[25/Sep/2025 17:10:57] "GET / HTTP/1.1" 200 2736
Not Found: /고양이
[25/Sep/2025 17:10:57] "GET /%EA%B3%A0%EC%96%91%EC%9D%B4 HTTP/1.1" 404 2652
[25/Sep/2025 17:10:59] "GET /photo/new/ HTTP/1.1" 200 1066
[25/Sep/2025 17:11:04] "GET /photo/2/ HTTP/1.1" 200 250
Not Found: /photo/2/고양이
[25/Sep/2025 17:11:04] "GET /photo/2/%EA%B3%A0%EC%96%91%EC%9D%B4 HTTP/1.1" 404 2676
C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 25, 2025 - 17:13:57
Django version 3.2.25, using settings 'myweb.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 25, 2025 - 17:14:54
Django version 3.2.25, using settings 'myweb.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[25/Sep/2025 17:16:01] "GET / HTTP/1.1" 200 2736
Not Found: /고양이
[25/Sep/2025 17:16:01] "GET /%EA%B3%A0%EC%96%91%EC%9D%B4 HTTP/1.1" 404 2844
[25/Sep/2025 17:16:03] "GET /photo/2/ HTTP/1.1" 200 299
Not Found: /photo/2/고양이
[25/Sep/2025 17:16:04] "GET /photo/2/%EA%B3%A0%EC%96%91%EC%9D%B4 HTTP/1.1" 404 2868
Internal Server Error: /photo/2/edit/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: photo_edit() got an unexpected keyword argument 'pk'
[25/Sep/2025 17:16:05] "GET /photo/2/edit/ HTTP/1.1" 500 60731
C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 25, 2025 - 17:17:26
Django version 3.2.25, using settings 'myweb.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[25/Sep/2025 17:17:28] "GET /photo/2/ HTTP/1.1" 200 299
Not Found: /photo/2/고양이
[25/Sep/2025 17:17:28] "GET /photo/2/%EA%B3%A0%EC%96%91%EC%9D%B4 HTTP/1.1" 404 2868
[25/Sep/2025 17:17:29] "GET /photo/2/edit/ HTTP/1.1" 200 1121
[25/Sep/2025 17:17:38] "POST /photo/2/edit/ HTTP/1.1" 200 1121
[25/Sep/2025 17:17:39] "POST /photo/2/edit/ HTTP/1.1" 200 1121
[25/Sep/2025 17:17:41] "GET / HTTP/1.1" 200 2736
Not Found: /고양이
[25/Sep/2025 17:17:41] "GET /%EA%B3%A0%EC%96%91%EC%9D%B4 HTTP/1.1" 404 2844
[25/Sep/2025 17:17:43] "GET /photo/2/ HTTP/1.1" 200 299
Not Found: /photo/2/고양이
[25/Sep/2025 17:17:43] "GET /photo/2/%EA%B3%A0%EC%96%91%EC%9D%B4 HTTP/1.1" 404 2868
[25/Sep/2025 17:17:44] "GET /photo/2/edit/ HTTP/1.1" 200 1121
C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\forms.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 25, 2025 - 17:18:29
Django version 3.2.25, using settings 'myweb.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[25/Sep/2025 17:18:34] "GET / HTTP/1.1" 200 2736
Not Found: /고양이
[25/Sep/2025 17:18:34] "GET /%EA%B3%A0%EC%96%91%EC%9D%B4 HTTP/1.1" 404 2844
[25/Sep/2025 17:18:35] "GET /photo/2/ HTTP/1.1" 200 299
Not Found: /photo/2/고양이
[25/Sep/2025 17:18:35] "GET /photo/2/%EA%B3%A0%EC%96%91%EC%9D%B4 HTTP/1.1" 404 2868
[25/Sep/2025 17:18:37] "GET /photo/2/edit/ HTTP/1.1" 200 1121
[25/Sep/2025 17:18:41] "POST /photo/2/edit/ HTTP/1.1" 200 1121
[25/Sep/2025 17:18:42] "GET / HTTP/1.1" 200 2736
Not Found: /고양이
[25/Sep/2025 17:18:42] "GET /%EA%B3%A0%EC%96%91%EC%9D%B4 HTTP/1.1" 404 2844
[25/Sep/2025 17:18:43] "GET /photo/2/ HTTP/1.1" 200 299
Not Found: /photo/2/고양이
[25/Sep/2025 17:18:43] "GET /photo/2/%EA%B3%A0%EC%96%91%EC%9D%B4 HTTP/1.1" 404 2868
[25/Sep/2025 17:18:47] "GET /photo/1/ HTTP/1.1" 200 375
[25/Sep/2025 17:18:48] "GET /photo/1/edit/ HTTP/1.1" 200 1191
[25/Sep/2025 17:18:53] "POST /photo/1/edit/ HTTP/1.1" 200 1191
[25/Sep/2025 17:18:54] "GET / HTTP/1.1" 200 2736
Not Found: /고양이
[25/Sep/2025 17:18:54] "GET /%EA%B3%A0%EC%96%91%EC%9D%B4 HTTP/1.1" 404 2844
[25/Sep/2025 17:18:55] "GET /photo/new/ HTTP/1.1" 200 1066
C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 25, 2025 - 17:22:42
Django version 3.2.25, using settings 'myweb.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[25/Sep/2025 17:22:48] "GET / HTTP/1.1" 200 2736
Not Found: /고양이
[25/Sep/2025 17:22:48] "GET /%EA%B3%A0%EC%96%91%EC%9D%B4 HTTP/1.1" 404 2844
[25/Sep/2025 17:22:49] "GET / HTTP/1.1" 200 2736
Not Found: /고양이
[25/Sep/2025 17:22:49] "GET /%EA%B3%A0%EC%96%91%EC%9D%B4 HTTP/1.1" 404 2844
[25/Sep/2025 17:22:49] "GET / HTTP/1.1" 200 2736
Not Found: /고양이
[25/Sep/2025 17:22:49] "GET /%EA%B3%A0%EC%96%91%EC%9D%B4 HTTP/1.1" 404 2844
[25/Sep/2025 17:22:49] "GET / HTTP/1.1" 200 2736
Not Found: /고양이
[25/Sep/2025 17:22:49] "GET /%EA%B3%A0%EC%96%91%EC%9D%B4 HTTP/1.1" 404 2844
[25/Sep/2025 17:22:51] "GET /photo/2/ HTTP/1.1" 200 299
Not Found: /photo/2/고양이
[25/Sep/2025 17:22:51] "GET /photo/2/%EA%B3%A0%EC%96%91%EC%9D%B4 HTTP/1.1" 404 2868
[25/Sep/2025 17:22:52] "GET /photo/2/edit/ HTTP/1.1" 200 1121
[25/Sep/2025 17:22:57] "POST /photo/2/edit/ HTTP/1.1" 200 1121
C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 25, 2025 - 17:26:40
Django version 3.2.25, using settings 'myweb.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 25, 2025 - 17:26:46
Django version 3.2.25, using settings 'myweb.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[25/Sep/2025 17:26:55] "GET / HTTP/1.1" 200 2736
Not Found: /고양이
[25/Sep/2025 17:26:55] "GET /%EA%B3%A0%EC%96%91%EC%9D%B4 HTTP/1.1" 404 2844
[25/Sep/2025 17:26:56] "GET /photo/1/ HTTP/1.1" 200 375
[25/Sep/2025 17:26:56] "GET /photo/1/edit/ HTTP/1.1" 200 1191
[25/Sep/2025 17:27:02] "POST /photo/1/edit/ HTTP/1.1" 302 0
[25/Sep/2025 17:27:02] "GET /photo/1/ HTTP/1.1" 200 483
[25/Sep/2025 17:27:11] "POST /photo/1/edit/ HTTP/1.1" 302 0
[25/Sep/2025 17:27:11] "GET /photo/1/ HTTP/1.1" 200 375
[25/Sep/2025 17:27:15] "GET /photo/new/ HTTP/1.1" 200 1066
[25/Sep/2025 17:27:17] "GET /photo/1/ HTTP/1.1" 200 375
[25/Sep/2025 17:27:20] "GET /photo/2/ HTTP/1.1" 200 299
Not Found: /photo/2/고양이
[25/Sep/2025 17:27:20] "GET /photo/2/%EA%B3%A0%EC%96%91%EC%9D%B4 HTTP/1.1" 404 2868
[25/Sep/2025 17:27:21] "GET /photo/2/edit/ HTTP/1.1" 200 1121
[25/Sep/2025 17:27:24] "POST /photo/2/edit/ HTTP/1.1" 302 0
[25/Sep/2025 17:27:24] "GET /photo/2/ HTTP/1.1" 200 323
Not Found: /photo/2/고양이ㅇㄹ
[25/Sep/2025 17:27:24] "GET /photo/2/%EA%B3%A0%EC%96%91%EC%9D%B4%E3%85%87%E3%84%B9 HTTP/1.1" 404 2898
C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\urls.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\management\commands\runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\management\base.py", line 419, in check
    all_issues = checks.run_checks(
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\checks\registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\urls\resolvers.py", line 416, in check
    for pattern in self.url_patterns:
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\urls\resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\urls\resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myweb\urls.py", line 21, in <module>
    path('', include('photo.urls')),
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\myvenv20\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\urls.py", line 19, in <module>
    path('photo/<int:pk>/remove/', views.photo_remove, name='photo_remove')
AttributeError: module 'photo.views' has no attribute 'photo_remove'
C:\Users\admin\Desktop\dev\Python-Practice\django\DRF_project\ch02_DRF_basic\photo\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 25, 2025 - 17:32:39
Django version 3.2.25, using settings 'myweb.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[25/Sep/2025 17:33:12] "GET /photo/1/ HTTP/1.1" 200 440
[25/Sep/2025 17:33:13] "GET /photo/1/remove/ HTTP/1.1" 200 403
[25/Sep/2025 17:33:16] "GET /photo/2/ HTTP/1.1" 200 388
Not Found: /photo/2/고양이ㅇㄹ
[25/Sep/2025 17:33:16] "GET /photo/2/%EA%B3%A0%EC%96%91%EC%9D%B4%E3%85%87%E3%84%B9 HTTP/1.1" 404 3094
[25/Sep/2025 17:33:17] "GET /photo/2/remove/ HTTP/1.1" 200 403
[25/Sep/2025 17:33:18] "POST /photo/2/remove/ HTTP/1.1" 302 0
[25/Sep/2025 17:33:18] "GET / HTTP/1.1" 200 2560
[25/Sep/2025 17:33:19] "GET /photo/3/ HTTP/1.1" 200 402
[25/Sep/2025 17:33:20] "GET /photo/3/remove/ HTTP/1.1" 200 397
[25/Sep/2025 17:33:21] "POST /photo/3/remove/ HTTP/1.1" 302 0
[25/Sep/2025 17:33:21] "GET / HTTP/1.1" 200 2346
[25/Sep/2025 17:33:23] "GET /photo/5/ HTTP/1.1" 200 559
[25/Sep/2025 17:33:24] "GET /photo/5/remove/ HTTP/1.1" 200 397
[25/Sep/2025 17:33:24] "POST /photo/5/remove/ HTTP/1.1" 302 0
[25/Sep/2025 17:33:24] "GET / HTTP/1.1" 200 1975
[25/Sep/2025 17:33:27] "GET /photo/4/ HTTP/1.1" 200 555
[25/Sep/2025 17:33:28] "GET /photo/4/remove/ HTTP/1.1" 200 397
[25/Sep/2025 17:33:28] "POST /photo/4/remove/ HTTP/1.1" 302 0
[25/Sep/2025 17:33:28] "GET / HTTP/1.1" 200 1608
[25/Sep/2025 17:33:29] "GET /photo/6/ HTTP/1.1" 200 555
[25/Sep/2025 17:33:30] "GET /photo/6/remove/ HTTP/1.1" 200 397
[25/Sep/2025 17:33:31] "POST /photo/6/remove/ HTTP/1.1" 302 0
[25/Sep/2025 17:33:31] "GET / HTTP/1.1" 200 1241
[25/Sep/2025 17:33:32] "GET /photo/7/ HTTP/1.1" 200 559
[25/Sep/2025 17:33:32] "GET /photo/7/remove/ HTTP/1.1" 200 397
[25/Sep/2025 17:33:33] "POST /photo/7/remove/ HTTP/1.1" 302 0
[25/Sep/2025 17:33:33] "GET / HTTP/1.1" 200 870
[25/Sep/2025 17:33:34] "GET /photo/8/ HTTP/1.1" 200 387
[25/Sep/2025 17:33:35] "GET /photo/8/remove/ HTTP/1.1" 200 397
[25/Sep/2025 17:33:35] "POST /photo/8/remove/ HTTP/1.1" 302 0
[25/Sep/2025 17:33:35] "GET / HTTP/1.1" 200 671